### PR TITLE
Added PlaybackRate support to increase or decrease the speed of the audio

### PR DESCRIPTION
**Pull request by catrielmuller**
A small commit to support handle the speed of the playback.

### CODE REVIEW

**Comment by wle8300** [comment]
Hi Catriel, gimme a few days to review this. Thx for contributing! 🙏

**Comment by catrielmuller** [comment]
Hi William, sure take your time

**Comment by wle8300** [comment]
@catrielmuller I believe we already have this feature. It's the `throttleMs` argument. It will limit the rate of the playback.

**Comment by catrielmuller** [comment]
@wle8300, No, this is to increase or decrease the speed of the sound, for example:
if you have a voice message of 1min length with the PlaybackRate on 2, it will take only 30 seconds to be played.

Reference https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate

**Comment by wle8300** [comment]
Hmmm I’m not sure this is something that is within the scope of this lib

**Pull request closed without merging**
